### PR TITLE
Removed target audience class

### LINKED ISSUE #227: Editorial object  has target audience pointing to old class
Editorial object :hasTargetAudience only :TargetAudience

Remove TargetAudience

Point to Audience

### PR DESCRIPTION
**Pull request by tormodv**
Moved pointers to Audience

Fix #227

### CODE REVIEW

**Comment by alexandre-rouxel** [comment]
Will be discussed in the Editorial Committee meeting, please see the issue.

**Review by alexandre-rouxel — COMMENTED** [review]
will be discussed further

**Review by JuergenGrupp — COMMENTED** [review]
Looks good to me. Let's discuss it in the committee meeting.

**Comment by JuergenGrupp** [comment]
Editorial Committee: We have agreed on this proposed solution.

**Pull request merged**
