### PR TITLE
Update ebucore.owl

### PR DESCRIPTION
**Pull request by tormodv**
Fix issue #68 

This time only that :)

### CODE REVIEW

**Comment by JuergenGrupp** [comment]
owl:FunctionalProperty has been added to the fileName property. If the effect of owl: FunctionalProperty is that absolutely all file names in a graph must be distinct, I am not sure whether all databases can guarantee that. If they can not, imho this classification is too strict. 
All other changes are fine for me.

**Comment by JuergenGrupp** [comment]
owl:FunctionalProperty has been added to the fileName property. If the effect of owl: FunctionalProperty is that absolutely all file names in a graph must be distinct, I am not sure whether all databases can guarantee that. If they can not, imho this classification is too strict. 
All other changes are fine for me.

**Comment by tormodv** [comment]
Not sure but in the w3c definition: "A functional property is a property that can have only one (unique) value y for each instance x, i.e. there cannot be two distinct values y1 and y2 such that the pairs (x,y1) and (x,y2) are both instances of this property."
So I think it means one value for each instance, ie some media file (the instance) has one file name.

**Review by JuergenGrupp — APPROVED** [review]
Fine for me.

**Review by alexandre-rouxel — APPROVED** [review]

**Comment by alexandre-rouxel** [comment]
approved

**Pull request merged**
