### PR TITLE
Introducing class restrictions

### PR DESCRIPTION
**Pull request by tormodv**
Introducing class restrictions in the model for generic properties like:@

- identifier
- name
- description
- type

### CODE REVIEW

**Comment by tormodv** [comment]
Can we merge the changes?

**Comment by JuergenGrupp** [comment]
Great Job, thank you! The Protege reasoners accept the owl file without any error.

**Review by JuergenGrupp — COMMENTED** [review]
Looks very good. Protege reasoners don't report a single error on this owl file.

**Comment by tormodv** [comment]
I guess you meant to merge, and not discard the changes :)

**Pull request merged**
